using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Grid;

namespace CascadeManager.CascadeFlowClient
{
	partial class FrmErrorList
	{
		private IContainer components = null;

		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
				components.Dispose();
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(FrmErrorList));
			gcErrors = new GridControl();
			gvErrors = new GridView();
			colFileName = new GridColumn();
			colError = new GridColumn();
			colComment = new GridColumn();
			repositoryItemCheckEdit1 = new RepositoryItemCheckEdit();
			gcErrors.BeginInit();
			gvErrors.BeginInit();
			repositoryItemCheckEdit1.BeginInit();
			SuspendLayout();
			componentResourceManager.ApplyResources(gcErrors, "gcErrors");
			gcErrors.EmbeddedNavigator.AccessibleDescription = componentResourceManager.GetString("gcErrors.EmbeddedNavigator.AccessibleDescription");
			gcErrors.EmbeddedNavigator.AccessibleName = componentResourceManager.GetString("gcErrors.EmbeddedNavigator.AccessibleName");
			gcErrors.EmbeddedNavigator.AllowHtmlTextInToolTip = (DefaultBoolean)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.AllowHtmlTextInToolTip");
			gcErrors.EmbeddedNavigator.Anchor = (AnchorStyles)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.Anchor");
			gcErrors.EmbeddedNavigator.BackgroundImage = (Image)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.BackgroundImage");
			gcErrors.EmbeddedNavigator.BackgroundImageLayout = (ImageLayout)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.BackgroundImageLayout");
			gcErrors.EmbeddedNavigator.ImeMode = (ImeMode)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.ImeMode");
			gcErrors.EmbeddedNavigator.MaximumSize = (Size)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.MaximumSize");
			gcErrors.EmbeddedNavigator.TextLocation = (NavigatorButtonsTextLocation)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.TextLocation");
			gcErrors.EmbeddedNavigator.ToolTip = componentResourceManager.GetString("gcErrors.EmbeddedNavigator.ToolTip");
			gcErrors.EmbeddedNavigator.ToolTipIconType = (ToolTipIconType)componentResourceManager.GetObject("gcErrors.EmbeddedNavigator.ToolTipIconType");
			gcErrors.EmbeddedNavigator.ToolTipTitle = componentResourceManager.GetString("gcErrors.EmbeddedNavigator.ToolTipTitle");
			gcErrors.LookAndFeel.SkinName = "Office 2007 Blue";
			gcErrors.MainView = gvErrors;
			gcErrors.Name = "gcErrors";
			gcErrors.RepositoryItems.AddRange(new RepositoryItem[1]
			{
		repositoryItemCheckEdit1
			});
			gcErrors.ViewCollection.AddRange(new BaseView[1]
			{
		gvErrors
			});
			gvErrors.Appearance.ColumnFilterButton.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.BackColor");
			gvErrors.Appearance.ColumnFilterButton.BackColor2 = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.BackColor2");
			gvErrors.Appearance.ColumnFilterButton.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.BorderColor");
			gvErrors.Appearance.ColumnFilterButton.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.Font");
			gvErrors.Appearance.ColumnFilterButton.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.FontSizeDelta");
			gvErrors.Appearance.ColumnFilterButton.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.FontStyleDelta");
			gvErrors.Appearance.ColumnFilterButton.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.ForeColor");
			gvErrors.Appearance.ColumnFilterButton.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.GradientMode");
			gvErrors.Appearance.ColumnFilterButton.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButton.Image");
			gvErrors.Appearance.ColumnFilterButton.Options.UseBackColor = true;
			gvErrors.Appearance.ColumnFilterButton.Options.UseBorderColor = true;
			gvErrors.Appearance.ColumnFilterButton.Options.UseFont = true;
			gvErrors.Appearance.ColumnFilterButton.Options.UseForeColor = true;
			gvErrors.Appearance.ColumnFilterButtonActive.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.BackColor");
			gvErrors.Appearance.ColumnFilterButtonActive.BackColor2 = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.BackColor2");
			gvErrors.Appearance.ColumnFilterButtonActive.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.BorderColor");
			gvErrors.Appearance.ColumnFilterButtonActive.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.Font");
			gvErrors.Appearance.ColumnFilterButtonActive.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.FontSizeDelta");
			gvErrors.Appearance.ColumnFilterButtonActive.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.FontStyleDelta");
			gvErrors.Appearance.ColumnFilterButtonActive.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.ForeColor");
			gvErrors.Appearance.ColumnFilterButtonActive.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.GradientMode");
			gvErrors.Appearance.ColumnFilterButtonActive.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.ColumnFilterButtonActive.Image");
			gvErrors.Appearance.ColumnFilterButtonActive.Options.UseBackColor = true;
			gvErrors.Appearance.ColumnFilterButtonActive.Options.UseBorderColor = true;
			gvErrors.Appearance.ColumnFilterButtonActive.Options.UseFont = true;
			gvErrors.Appearance.ColumnFilterButtonActive.Options.UseForeColor = true;
			gvErrors.Appearance.CustomizationFormHint.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.CustomizationFormHint.Font");
			gvErrors.Appearance.CustomizationFormHint.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.CustomizationFormHint.FontSizeDelta");
			gvErrors.Appearance.CustomizationFormHint.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.CustomizationFormHint.FontStyleDelta");
			gvErrors.Appearance.CustomizationFormHint.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.CustomizationFormHint.GradientMode");
			gvErrors.Appearance.CustomizationFormHint.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.CustomizationFormHint.Image");
			gvErrors.Appearance.CustomizationFormHint.Options.UseFont = true;
			gvErrors.Appearance.DetailTip.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.DetailTip.Font");
			gvErrors.Appearance.DetailTip.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.DetailTip.FontSizeDelta");
			gvErrors.Appearance.DetailTip.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.DetailTip.FontStyleDelta");
			gvErrors.Appearance.DetailTip.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.DetailTip.GradientMode");
			gvErrors.Appearance.DetailTip.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.DetailTip.Image");
			gvErrors.Appearance.DetailTip.Options.UseFont = true;
			gvErrors.Appearance.Empty.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.Empty.BackColor");
			gvErrors.Appearance.Empty.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.Empty.Font");
			gvErrors.Appearance.Empty.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.Empty.FontSizeDelta");
			gvErrors.Appearance.Empty.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.Empty.FontStyleDelta");
			gvErrors.Appearance.Empty.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.Empty.GradientMode");
			gvErrors.Appearance.Empty.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.Empty.Image");
			gvErrors.Appearance.Empty.Options.UseBackColor = true;
			gvErrors.Appearance.Empty.Options.UseFont = true;
			gvErrors.Appearance.EvenRow.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.EvenRow.BackColor");
			gvErrors.Appearance.EvenRow.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.EvenRow.Font");
			gvErrors.Appearance.EvenRow.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.EvenRow.FontSizeDelta");
			gvErrors.Appearance.EvenRow.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.EvenRow.FontStyleDelta");
			gvErrors.Appearance.EvenRow.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.EvenRow.ForeColor");
			gvErrors.Appearance.EvenRow.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.EvenRow.GradientMode");
			gvErrors.Appearance.EvenRow.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.EvenRow.Image");
			gvErrors.Appearance.EvenRow.Options.UseBackColor = true;
			gvErrors.Appearance.EvenRow.Options.UseFont = true;
			gvErrors.Appearance.EvenRow.Options.UseForeColor = true;
			gvErrors.Appearance.FilterCloseButton.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.BackColor");
			gvErrors.Appearance.FilterCloseButton.BackColor2 = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.BackColor2");
			gvErrors.Appearance.FilterCloseButton.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.BorderColor");
			gvErrors.Appearance.FilterCloseButton.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.Font");
			gvErrors.Appearance.FilterCloseButton.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.FontSizeDelta");
			gvErrors.Appearance.FilterCloseButton.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.FontStyleDelta");
			gvErrors.Appearance.FilterCloseButton.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.ForeColor");
			gvErrors.Appearance.FilterCloseButton.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.GradientMode");
			gvErrors.Appearance.FilterCloseButton.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.FilterCloseButton.Image");
			gvErrors.Appearance.FilterCloseButton.Options.UseBackColor = true;
			gvErrors.Appearance.FilterCloseButton.Options.UseBorderColor = true;
			gvErrors.Appearance.FilterCloseButton.Options.UseFont = true;
			gvErrors.Appearance.FilterCloseButton.Options.UseForeColor = true;
			gvErrors.Appearance.FilterPanel.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FilterPanel.BackColor");
			gvErrors.Appearance.FilterPanel.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.FilterPanel.Font");
			gvErrors.Appearance.FilterPanel.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.FilterPanel.FontSizeDelta");
			gvErrors.Appearance.FilterPanel.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.FilterPanel.FontStyleDelta");
			gvErrors.Appearance.FilterPanel.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FilterPanel.ForeColor");
			gvErrors.Appearance.FilterPanel.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.FilterPanel.GradientMode");
			gvErrors.Appearance.FilterPanel.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.FilterPanel.Image");
			gvErrors.Appearance.FilterPanel.Options.UseBackColor = true;
			gvErrors.Appearance.FilterPanel.Options.UseFont = true;
			gvErrors.Appearance.FilterPanel.Options.UseForeColor = true;
			gvErrors.Appearance.FixedLine.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FixedLine.BackColor");
			gvErrors.Appearance.FixedLine.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.FixedLine.Font");
			gvErrors.Appearance.FixedLine.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.FixedLine.FontSizeDelta");
			gvErrors.Appearance.FixedLine.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.FixedLine.FontStyleDelta");
			gvErrors.Appearance.FixedLine.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.FixedLine.GradientMode");
			gvErrors.Appearance.FixedLine.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.FixedLine.Image");
			gvErrors.Appearance.FixedLine.Options.UseBackColor = true;
			gvErrors.Appearance.FixedLine.Options.UseFont = true;
			gvErrors.Appearance.FocusedCell.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FocusedCell.BackColor");
			gvErrors.Appearance.FocusedCell.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.FocusedCell.Font");
			gvErrors.Appearance.FocusedCell.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.FocusedCell.FontSizeDelta");
			gvErrors.Appearance.FocusedCell.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.FocusedCell.FontStyleDelta");
			gvErrors.Appearance.FocusedCell.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FocusedCell.ForeColor");
			gvErrors.Appearance.FocusedCell.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.FocusedCell.GradientMode");
			gvErrors.Appearance.FocusedCell.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.FocusedCell.Image");
			gvErrors.Appearance.FocusedCell.Options.UseBackColor = true;
			gvErrors.Appearance.FocusedCell.Options.UseFont = true;
			gvErrors.Appearance.FocusedCell.Options.UseForeColor = true;
			gvErrors.Appearance.FocusedRow.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FocusedRow.BackColor");
			gvErrors.Appearance.FocusedRow.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.FocusedRow.Font");
			gvErrors.Appearance.FocusedRow.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.FocusedRow.FontSizeDelta");
			gvErrors.Appearance.FocusedRow.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.FocusedRow.FontStyleDelta");
			gvErrors.Appearance.FocusedRow.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FocusedRow.ForeColor");
			gvErrors.Appearance.FocusedRow.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.FocusedRow.GradientMode");
			gvErrors.Appearance.FocusedRow.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.FocusedRow.Image");
			gvErrors.Appearance.FocusedRow.Options.UseBackColor = true;
			gvErrors.Appearance.FocusedRow.Options.UseFont = true;
			gvErrors.Appearance.FocusedRow.Options.UseForeColor = true;
			gvErrors.Appearance.FooterPanel.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.BackColor");
			gvErrors.Appearance.FooterPanel.BackColor2 = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.BackColor2");
			gvErrors.Appearance.FooterPanel.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.BorderColor");
			gvErrors.Appearance.FooterPanel.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.Font");
			gvErrors.Appearance.FooterPanel.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.FontSizeDelta");
			gvErrors.Appearance.FooterPanel.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.FontStyleDelta");
			gvErrors.Appearance.FooterPanel.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.ForeColor");
			gvErrors.Appearance.FooterPanel.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.GradientMode");
			gvErrors.Appearance.FooterPanel.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.FooterPanel.Image");
			gvErrors.Appearance.FooterPanel.Options.UseBackColor = true;
			gvErrors.Appearance.FooterPanel.Options.UseBorderColor = true;
			gvErrors.Appearance.FooterPanel.Options.UseFont = true;
			gvErrors.Appearance.FooterPanel.Options.UseForeColor = true;
			gvErrors.Appearance.GroupButton.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.BackColor");
			gvErrors.Appearance.GroupButton.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.BorderColor");
			gvErrors.Appearance.GroupButton.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.Font");
			gvErrors.Appearance.GroupButton.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.FontSizeDelta");
			gvErrors.Appearance.GroupButton.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.FontStyleDelta");
			gvErrors.Appearance.GroupButton.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.ForeColor");
			gvErrors.Appearance.GroupButton.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.GradientMode");
			gvErrors.Appearance.GroupButton.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.GroupButton.Image");
			gvErrors.Appearance.GroupButton.Options.UseBackColor = true;
			gvErrors.Appearance.GroupButton.Options.UseBorderColor = true;
			gvErrors.Appearance.GroupButton.Options.UseFont = true;
			gvErrors.Appearance.GroupButton.Options.UseForeColor = true;
			gvErrors.Appearance.GroupFooter.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.BackColor");
			gvErrors.Appearance.GroupFooter.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.BorderColor");
			gvErrors.Appearance.GroupFooter.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.Font");
			gvErrors.Appearance.GroupFooter.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.FontSizeDelta");
			gvErrors.Appearance.GroupFooter.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.FontStyleDelta");
			gvErrors.Appearance.GroupFooter.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.ForeColor");
			gvErrors.Appearance.GroupFooter.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.GradientMode");
			gvErrors.Appearance.GroupFooter.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.GroupFooter.Image");
			gvErrors.Appearance.GroupFooter.Options.UseBackColor = true;
			gvErrors.Appearance.GroupFooter.Options.UseBorderColor = true;
			gvErrors.Appearance.GroupFooter.Options.UseFont = true;
			gvErrors.Appearance.GroupFooter.Options.UseForeColor = true;
			gvErrors.Appearance.GroupPanel.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupPanel.BackColor");
			gvErrors.Appearance.GroupPanel.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.GroupPanel.Font");
			gvErrors.Appearance.GroupPanel.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.GroupPanel.FontSizeDelta");
			gvErrors.Appearance.GroupPanel.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.GroupPanel.FontStyleDelta");
			gvErrors.Appearance.GroupPanel.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupPanel.ForeColor");
			gvErrors.Appearance.GroupPanel.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.GroupPanel.GradientMode");
			gvErrors.Appearance.GroupPanel.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.GroupPanel.Image");
			gvErrors.Appearance.GroupPanel.Options.UseBackColor = true;
			gvErrors.Appearance.GroupPanel.Options.UseFont = true;
			gvErrors.Appearance.GroupPanel.Options.UseForeColor = true;
			gvErrors.Appearance.GroupRow.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.BackColor");
			gvErrors.Appearance.GroupRow.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.BorderColor");
			gvErrors.Appearance.GroupRow.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.Font");
			gvErrors.Appearance.GroupRow.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.FontSizeDelta");
			gvErrors.Appearance.GroupRow.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.FontStyleDelta");
			gvErrors.Appearance.GroupRow.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.ForeColor");
			gvErrors.Appearance.GroupRow.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.GradientMode");
			gvErrors.Appearance.GroupRow.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.GroupRow.Image");
			gvErrors.Appearance.GroupRow.Options.UseBackColor = true;
			gvErrors.Appearance.GroupRow.Options.UseBorderColor = true;
			gvErrors.Appearance.GroupRow.Options.UseFont = true;
			gvErrors.Appearance.GroupRow.Options.UseForeColor = true;
			gvErrors.Appearance.HeaderPanel.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.BackColor");
			gvErrors.Appearance.HeaderPanel.BackColor2 = (Color)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.BackColor2");
			gvErrors.Appearance.HeaderPanel.BorderColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.BorderColor");
			gvErrors.Appearance.HeaderPanel.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.Font");
			gvErrors.Appearance.HeaderPanel.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.FontSizeDelta");
			gvErrors.Appearance.HeaderPanel.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.FontStyleDelta");
			gvErrors.Appearance.HeaderPanel.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.ForeColor");
			gvErrors.Appearance.HeaderPanel.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.GradientMode");
			gvErrors.Appearance.HeaderPanel.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.HeaderPanel.Image");
			gvErrors.Appearance.HeaderPanel.Options.UseBackColor = true;
			gvErrors.Appearance.HeaderPanel.Options.UseBorderColor = true;
			gvErrors.Appearance.HeaderPanel.Options.UseFont = true;
			gvErrors.Appearance.HeaderPanel.Options.UseForeColor = true;
			gvErrors.Appearance.HideSelectionRow.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.HideSelectionRow.BackColor");
			gvErrors.Appearance.HideSelectionRow.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.HideSelectionRow.Font");
			gvErrors.Appearance.HideSelectionRow.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.HideSelectionRow.FontSizeDelta");
			gvErrors.Appearance.HideSelectionRow.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.HideSelectionRow.FontStyleDelta");
			gvErrors.Appearance.HideSelectionRow.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.HideSelectionRow.ForeColor");
			gvErrors.Appearance.HideSelectionRow.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.HideSelectionRow.GradientMode");
			gvErrors.Appearance.HideSelectionRow.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.HideSelectionRow.Image");
			gvErrors.Appearance.HideSelectionRow.Options.UseBackColor = true;
			gvErrors.Appearance.HideSelectionRow.Options.UseFont = true;
			gvErrors.Appearance.HideSelectionRow.Options.UseForeColor = true;
			gvErrors.Appearance.HorzLine.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.HorzLine.BackColor");
			gvErrors.Appearance.HorzLine.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.HorzLine.Font");
			gvErrors.Appearance.HorzLine.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.HorzLine.FontSizeDelta");
			gvErrors.Appearance.HorzLine.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.HorzLine.FontStyleDelta");
			gvErrors.Appearance.HorzLine.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.HorzLine.GradientMode");
			gvErrors.Appearance.HorzLine.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.HorzLine.Image");
			gvErrors.Appearance.HorzLine.Options.UseBackColor = true;
			gvErrors.Appearance.HorzLine.Options.UseFont = true;
			gvErrors.Appearance.OddRow.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.OddRow.BackColor");
			gvErrors.Appearance.OddRow.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.OddRow.Font");
			gvErrors.Appearance.OddRow.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.OddRow.FontSizeDelta");
			gvErrors.Appearance.OddRow.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.OddRow.FontStyleDelta");
			gvErrors.Appearance.OddRow.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.OddRow.ForeColor");
			gvErrors.Appearance.OddRow.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.OddRow.GradientMode");
			gvErrors.Appearance.OddRow.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.OddRow.Image");
			gvErrors.Appearance.OddRow.Options.UseBackColor = true;
			gvErrors.Appearance.OddRow.Options.UseFont = true;
			gvErrors.Appearance.OddRow.Options.UseForeColor = true;
			gvErrors.Appearance.Preview.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.Preview.BackColor");
			gvErrors.Appearance.Preview.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.Preview.Font");
			gvErrors.Appearance.Preview.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.Preview.FontSizeDelta");
			gvErrors.Appearance.Preview.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.Preview.FontStyleDelta");
			gvErrors.Appearance.Preview.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.Preview.ForeColor");
			gvErrors.Appearance.Preview.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.Preview.GradientMode");
			gvErrors.Appearance.Preview.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.Preview.Image");
			gvErrors.Appearance.Preview.Options.UseBackColor = true;
			gvErrors.Appearance.Preview.Options.UseFont = true;
			gvErrors.Appearance.Preview.Options.UseForeColor = true;
			gvErrors.Appearance.Row.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.Row.BackColor");
			gvErrors.Appearance.Row.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.Row.Font");
			gvErrors.Appearance.Row.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.Row.FontSizeDelta");
			gvErrors.Appearance.Row.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.Row.FontStyleDelta");
			gvErrors.Appearance.Row.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.Row.ForeColor");
			gvErrors.Appearance.Row.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.Row.GradientMode");
			gvErrors.Appearance.Row.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.Row.Image");
			gvErrors.Appearance.Row.Options.UseBackColor = true;
			gvErrors.Appearance.Row.Options.UseFont = true;
			gvErrors.Appearance.Row.Options.UseForeColor = true;
			gvErrors.Appearance.RowSeparator.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.RowSeparator.BackColor");
			gvErrors.Appearance.RowSeparator.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.RowSeparator.Font");
			gvErrors.Appearance.RowSeparator.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.RowSeparator.FontSizeDelta");
			gvErrors.Appearance.RowSeparator.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.RowSeparator.FontStyleDelta");
			gvErrors.Appearance.RowSeparator.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.RowSeparator.GradientMode");
			gvErrors.Appearance.RowSeparator.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.RowSeparator.Image");
			gvErrors.Appearance.RowSeparator.Options.UseBackColor = true;
			gvErrors.Appearance.RowSeparator.Options.UseFont = true;
			gvErrors.Appearance.SelectedRow.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.SelectedRow.BackColor");
			gvErrors.Appearance.SelectedRow.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.SelectedRow.Font");
			gvErrors.Appearance.SelectedRow.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.SelectedRow.FontSizeDelta");
			gvErrors.Appearance.SelectedRow.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.SelectedRow.FontStyleDelta");
			gvErrors.Appearance.SelectedRow.ForeColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.SelectedRow.ForeColor");
			gvErrors.Appearance.SelectedRow.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.SelectedRow.GradientMode");
			gvErrors.Appearance.SelectedRow.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.SelectedRow.Image");
			gvErrors.Appearance.SelectedRow.Options.UseBackColor = true;
			gvErrors.Appearance.SelectedRow.Options.UseFont = true;
			gvErrors.Appearance.SelectedRow.Options.UseForeColor = true;
			gvErrors.Appearance.TopNewRow.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.TopNewRow.Font");
			gvErrors.Appearance.TopNewRow.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.TopNewRow.FontSizeDelta");
			gvErrors.Appearance.TopNewRow.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.TopNewRow.FontStyleDelta");
			gvErrors.Appearance.TopNewRow.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.TopNewRow.GradientMode");
			gvErrors.Appearance.TopNewRow.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.TopNewRow.Image");
			gvErrors.Appearance.TopNewRow.Options.UseFont = true;
			gvErrors.Appearance.VertLine.BackColor = (Color)componentResourceManager.GetObject("gvErrors.Appearance.VertLine.BackColor");
			gvErrors.Appearance.VertLine.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.VertLine.Font");
			gvErrors.Appearance.VertLine.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.VertLine.FontSizeDelta");
			gvErrors.Appearance.VertLine.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.VertLine.FontStyleDelta");
			gvErrors.Appearance.VertLine.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.VertLine.GradientMode");
			gvErrors.Appearance.VertLine.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.VertLine.Image");
			gvErrors.Appearance.VertLine.Options.UseBackColor = true;
			gvErrors.Appearance.VertLine.Options.UseFont = true;
			gvErrors.Appearance.ViewCaption.Font = (Font)componentResourceManager.GetObject("gvErrors.Appearance.ViewCaption.Font");
			gvErrors.Appearance.ViewCaption.FontSizeDelta = (int)componentResourceManager.GetObject("gvErrors.Appearance.ViewCaption.FontSizeDelta");
			gvErrors.Appearance.ViewCaption.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("gvErrors.Appearance.ViewCaption.FontStyleDelta");
			gvErrors.Appearance.ViewCaption.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("gvErrors.Appearance.ViewCaption.GradientMode");
			gvErrors.Appearance.ViewCaption.Image = (Image)componentResourceManager.GetObject("gvErrors.Appearance.ViewCaption.Image");
			gvErrors.Appearance.ViewCaption.Options.UseFont = true;
			componentResourceManager.ApplyResources(gvErrors, "gvErrors");
			gvErrors.Columns.AddRange(new GridColumn[3]
			{
		colFileName,
		colError,
		colComment
			});
			gvErrors.GridControl = gcErrors;
			gvErrors.Name = "gvErrors";
			gvErrors.OptionsCustomization.AllowFilter = false;
			gvErrors.OptionsFind.ClearFindOnClose = false;
			gvErrors.OptionsFind.FindDelay = 10000;
			gvErrors.OptionsFind.FindMode = FindMode.Always;
			gvErrors.OptionsFind.ShowCloseButton = false;
			gvErrors.OptionsSelection.MultiSelect = true;
			gvErrors.OptionsView.EnableAppearanceEvenRow = true;
			gvErrors.OptionsView.EnableAppearanceOddRow = true;
			gvErrors.OptionsView.ShowGroupPanel = false;
			colFileName.AppearanceCell.Font = (Font)componentResourceManager.GetObject("colFileName.AppearanceCell.Font");
			colFileName.AppearanceCell.FontSizeDelta = (int)componentResourceManager.GetObject("colFileName.AppearanceCell.FontSizeDelta");
			colFileName.AppearanceCell.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("colFileName.AppearanceCell.FontStyleDelta");
			colFileName.AppearanceCell.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("colFileName.AppearanceCell.GradientMode");
			colFileName.AppearanceCell.Image = (Image)componentResourceManager.GetObject("colFileName.AppearanceCell.Image");
			colFileName.AppearanceCell.Options.UseFont = true;
			colFileName.AppearanceHeader.Font = (Font)componentResourceManager.GetObject("colFileName.AppearanceHeader.Font");
			colFileName.AppearanceHeader.FontSizeDelta = (int)componentResourceManager.GetObject("colFileName.AppearanceHeader.FontSizeDelta");
			colFileName.AppearanceHeader.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("colFileName.AppearanceHeader.FontStyleDelta");
			colFileName.AppearanceHeader.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("colFileName.AppearanceHeader.GradientMode");
			colFileName.AppearanceHeader.Image = (Image)componentResourceManager.GetObject("colFileName.AppearanceHeader.Image");
			colFileName.AppearanceHeader.Options.UseFont = true;
			colFileName.AppearanceHeader.Options.UseTextOptions = true;
			colFileName.AppearanceHeader.TextOptions.HAlignment = HorzAlignment.Center;
			componentResourceManager.ApplyResources(colFileName, "colFileName");
			colFileName.FieldName = "FileName";
			colFileName.Name = "colFileName";
			colFileName.OptionsColumn.AllowSort = DefaultBoolean.False;
			colFileName.OptionsColumn.FixedWidth = true;
			colError.AppearanceCell.Font = (Font)componentResourceManager.GetObject("colError.AppearanceCell.Font");
			colError.AppearanceCell.FontSizeDelta = (int)componentResourceManager.GetObject("colError.AppearanceCell.FontSizeDelta");
			colError.AppearanceCell.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("colError.AppearanceCell.FontStyleDelta");
			colError.AppearanceCell.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("colError.AppearanceCell.GradientMode");
			colError.AppearanceCell.Image = (Image)componentResourceManager.GetObject("colError.AppearanceCell.Image");
			colError.AppearanceCell.Options.UseFont = true;
			colError.AppearanceHeader.Font = (Font)componentResourceManager.GetObject("colError.AppearanceHeader.Font");
			colError.AppearanceHeader.FontSizeDelta = (int)componentResourceManager.GetObject("colError.AppearanceHeader.FontSizeDelta");
			colError.AppearanceHeader.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("colError.AppearanceHeader.FontStyleDelta");
			colError.AppearanceHeader.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("colError.AppearanceHeader.GradientMode");
			colError.AppearanceHeader.Image = (Image)componentResourceManager.GetObject("colError.AppearanceHeader.Image");
			colError.AppearanceHeader.Options.UseFont = true;
			componentResourceManager.ApplyResources(colError, "colError");
			colError.FieldName = "Error";
			colError.Name = "colError";
			colError.OptionsColumn.FixedWidth = true;
			colComment.AppearanceCell.Font = (Font)componentResourceManager.GetObject("colComment.AppearanceCell.Font");
			colComment.AppearanceCell.FontSizeDelta = (int)componentResourceManager.GetObject("colComment.AppearanceCell.FontSizeDelta");
			colComment.AppearanceCell.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("colComment.AppearanceCell.FontStyleDelta");
			colComment.AppearanceCell.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("colComment.AppearanceCell.GradientMode");
			colComment.AppearanceCell.Image = (Image)componentResourceManager.GetObject("colComment.AppearanceCell.Image");
			colComment.AppearanceCell.Options.UseFont = true;
			colComment.AppearanceHeader.Font = (Font)componentResourceManager.GetObject("colComment.AppearanceHeader.Font");
			colComment.AppearanceHeader.FontSizeDelta = (int)componentResourceManager.GetObject("colComment.AppearanceHeader.FontSizeDelta");
			colComment.AppearanceHeader.FontStyleDelta = (FontStyle)componentResourceManager.GetObject("colComment.AppearanceHeader.FontStyleDelta");
			colComment.AppearanceHeader.GradientMode = (LinearGradientMode)componentResourceManager.GetObject("colComment.AppearanceHeader.GradientMode");
			colComment.AppearanceHeader.Image = (Image)componentResourceManager.GetObject("colComment.AppearanceHeader.Image");
			colComment.AppearanceHeader.Options.UseFont = true;
			componentResourceManager.ApplyResources(colComment, "colComment");
			colComment.FieldName = "Comment";
			colComment.Name = "colComment";
			colComment.OptionsColumn.FixedWidth = true;
			componentResourceManager.ApplyResources(repositoryItemCheckEdit1, "repositoryItemCheckEdit1");
			repositoryItemCheckEdit1.Name = "repositoryItemCheckEdit1";
			componentResourceManager.ApplyResources(this, "$this");
			AutoScaleMode = AutoScaleMode.Font;
			Controls.Add(gcErrors);
			Name = "FrmErrorList";
			Load += frmErrorList_Load;
			gcErrors.EndInit();
			gvErrors.EndInit();
			repositoryItemCheckEdit1.EndInit();
			ResumeLayout(false);
		}

		private GridControl gcErrors;
		private GridView gvErrors;
		private GridColumn colFileName;
		private RepositoryItemCheckEdit repositoryItemCheckEdit1;
		private GridColumn colError;
		private GridColumn colComment;
	}
}
