//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Diagnostics;

namespace CascadeManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
	{
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default
		{
            get
			{
                return defaultInstance;
            }
        }

		[UserScopedSetting, DebuggerNonUserCode, DefaultSettingValue("ru-Ru")]
	    public string Language
	    {
		    get
		    {
			    return (string) this["Language"];			    
		    }

		    set
		    {
			    this["Language"] = value;
		    }
	    }
    }
}
